[Bend]
authors = ["NaoEhSavio"]
language = "en"
multilingual = false
src = "src"
title = "Bend-Book"

[build]
build-dir = "./docs"
use-default-preprocessors = false

[preprocessor.index]

[preprocessor.links]

[output.html]
mathjax-support = true